### ISSUE TITLE
Add LDD Info-X (and Master ?) in code list or add a search input

### ISSUE THREAD

**Issue by OrnithOrtion** [Matunknown/timetable-viewer-evry#1]
Hello @Matunknown !

Well done for your pretty application.

## Context

I faced an issue with the legacy `VT Agenda` and Firefox (my daily web browser). With some recent version of the software, it seems that the default line-height is bigger than usually, and thus the student login form is broken (some line break html tags `<br>` do some bad stuff).

I am going to send a ticket to the disi-assistance portal, to warn them about this thing.

The fix is really straight forward, and there is several ways: remove `<br>` and improve a little this old css (probably a gentle dream...) or inject a litle line of css (really easy with Nginx, for instance, or locally using a navigator css injection extension): 

```css
br+br {
  display: none;
}
```
for a relatively simple, altough working example.

##  Ask

Can you add the entry 'L2LDDISDV' (the current code for second year promotion of bionfo "Double Licence", NB, It seems that the last year 'LDD1SDVI' code works for newcomers.

Maybe it could be easier to implement a simple search form (with an indexer search engine, or only json code list, for all known codes, populated in the code).

Thank you for your help, and work for the community ;-)

**Comment by Matunknown** [comment]
Hi, thanks for your interest in my application, I just made some updates on the site, I added the code `L2LDDISDV`.

I will think about the proposal of the search form, I intend anyway to improve the app continuously, I take all ideas and remarks with great a pleasure.
